
export const Renderer_Events = {
  START_DOWNLOAD:"START_DOWNLOAD",
  OPEN_FOLDER:"OPEN_FOLDER"
}

export const Main_Events = {
  ADD_SINGLE_DOWNLOAD_ITEM:"ADD_DOWNLOAD_ITEM",
  ADD_PLAYLIST_DOWNLOAD_ITEM:"ADD_PLAYLIST_DOWNLOAD_ITEM",
  HANDLE_PROGRESS: 'HANDLE_PROGRESS',
  HANDLE_COMPLETE: 'HANDLE_COMPLETE',
}

