
export const Renderer_Events = {
  START_DOWNLOAD:"START_DOWNLOAD",
  START_PLAYLIST_DOWNLOAD:"START_PLAYLIST_DOWNLOAD",
  OPEN_FOLDER:"OPEN_FOLDER",
  FETCH_SINGLE_VIDEO_INFO:"FETCH_SINGLE_VIDEO_INFO",
  DOWNLOAD_PLALIST_VIDEO:"DOWNLOAD_PLALIST_VIDEO",
  FETCH_PLAYLIST_INFO:"FETCH_PLAYLIST_INFO",
  DOWNLOAD_SINGLE_VIDEO_FROM_INFO:"DOWNLOAD_SINGLE_VIDEO_FROM_INFO",
}

export const Main_Events = {
  ADD_SINGLE_DOWNLOAD_ITEM:"ADD_DOWNLOAD_ITEM",
  ADD_PLAYLIST_DOWNLOAD_ITEM:"ADD_PLAYLIST_DOWNLOAD_ITEM",
  HANDLE_PROGRESS_: 'HANDLE_PROGRESS_',
  HANDLE_COMPLETE_: 'HANDLE_COMPLETE_',
  ON_SINGLE_VIDEO_INFO_FETCH_COMPLETE: 'ON_SINGLE_VIDEO_INFO_FETCH_COMPLETE_',
  HANDLE_PLAYLIST_FETCH_COMPLETE_: 'HANDLE_PLAYLIST_FETCH_COMPLETE_',
  HANDLE_SINGLE_VIDEO_FETCH_COMPLETE_: 'HANDLE_SINGLE_VIDEO_FETCH_COMPLETE_'
}

export const Constants={
  URL_PREFIX:"https://www.youtube.com/watch?v=",
}

